[workspace]
members = [
    "openmls",
    "traits",
    "openmls_rust_crypto",
    "fuzz",
    "cli",
    "interop_client",
    "memory_keystore",
    "delivery-service/ds",
    "delivery-service/ds-lib",
    "basic_credential",
]
resolver = "2"

# Central dependency management for some crates
[workspace.dependencies]
tls_codec = { version = "0.4.0-pre.2", features = [
    "derive",
    "serde",
    "mls",
    "conditional_deserialization",
], git = 'https://github.com/kkohbrok/formats.git', branch = "konrad/pub_macro" }
